// Code generated by xgen. DO NOT EDIT.

package mpd

// KeyIdType ...
type KeyIdType string

// KeyIdListType ...
type KeyIdListType []string

// DefaultKID ...
type DefaultKID *KeyIdListType

// Pssh ...
type Pssh string
