// Code generated by xgen. DO NOT EDIT.

package mpd

// UrlQueryInfo ...
type UrlQueryInfo *UrlQueryInfoType

// UrlQueryInfoType ...
type UrlQueryInfoType struct {
	QueryTemplate  string   `xml:"queryTemplate,attr,omitempty"`
	UseMPDUrlQuery bool     `xml:"useMPDUrlQuery,attr,omitempty"`
	QueryString    string   `xml:"queryString,attr,omitempty"`
	XlinkHref      *Href    `xml:"xlink:href,attr,omitempty"`
	XlinkActuate   *Actuate `xml:"xlink:actuate,attr,omitempty"`
	XlinkType      *Type    `xml:"xlink:type,attr,omitempty"`
	XlinkShow      *Show    `xml:"xlink:show,attr,omitempty"`
}

// ExtUrlQueryInfo ...
type ExtUrlQueryInfo *ExtendedUrlInfoType

// ExtHttpHeaderInfo ...
type ExtHttpHeaderInfo *ExtendedUrlInfoType

// ExtendedUrlInfoType ...
type ExtendedUrlInfoType struct {
	IncludeInRequests string `xml:"includeInRequests,attr,omitempty"`
	HeaderParamSource string `xml:"headerParamSource,attr,omitempty"`
	SameOriginOnly    bool   `xml:"sameOriginOnly,attr,omitempty"`
	*UrlQueryInfoType
}
