// Code generated by xgen. DO NOT EDIT.

package mpd

// Patch ...
type Patch interface{}

// PatchType ...
type PatchType struct {
	MpdId               string        `xml:"mpdId,attr"`
	PublishTime         string        `xml:"publishTime,attr"`
	OriginalPublishTime string        `xml:"originalPublishTime,attr"`
	Add                 []interface{} `xml:"add"`
	Remove              []interface{} `xml:"remove"`
	Replace             []interface{} `xml:"replace"`
}
